# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.5.0.3
group=com.maniake.scmc
java_version=21
config_version=0.9.6.0-6061017d
minecraft_version=1.21.8
mod_name=SCMC [Server Client Mod Checker]
mod_author=Studio Maniake
mod_id=scmc
license=CC0-1.0
credits=Studio Maniake
description=A mod intended for dedicated servers to ensure players get the right mods before playing!
modrinthID = HYGvfYUl
modrinthTOKEN = mrp_fksRSuDhVwpt7hB82Ng6AXHlvLBRq3iMCYGcqjmIOoqqJdF12NXpPtlDdtgj
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.caching=false